[package]
name = "advent_of_code_solver"
version = "0.1.0"
authors = ["AsamK"]
edition = "2018"

[dependencies]
clap = "2"
chrono = "0.4"
nom = "5"
xdg = "2"
toml = "0.5"
serde = { version = '1', features = ['derive'] }
reqwest = "0.9"
rayon = "1"
